// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuhvRGG0NY56NsSgJVUCGKNNGv_JPdHtE',
    appId: '1:925807401475:web:6bcf24dc13addbee4f4c36',
    messagingSenderId: '925807401475',
    projectId: 'quickdeliver-d5e46',
    authDomain: 'quickdeliver-d5e46.firebaseapp.com',
    storageBucket: 'quickdeliver-d5e46.firebasestorage.app',
    measurementId: 'G-FSTQ78MW0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU78zMuCBGc2vXpme3-sf6Qj8FTDguO4k',
    appId: '1:925807401475:android:53f68ca0e64647814f4c36',
    messagingSenderId: '925807401475',
    projectId: 'quickdeliver-d5e46',
    storageBucket: 'quickdeliver-d5e46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-0WTnUNwCwEhpFri8qGIRX5EzfA4gcs',
    appId: '1:925807401475:ios:e545bd23cdb2a6274f4c36',
    messagingSenderId: '925807401475',
    projectId: 'quickdeliver-d5e46',
    storageBucket: 'quickdeliver-d5e46.firebasestorage.app',
    iosBundleId: 'com.example.quickdeliverFlutterChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-0WTnUNwCwEhpFri8qGIRX5EzfA4gcs',
    appId: '1:925807401475:ios:e545bd23cdb2a6274f4c36',
    messagingSenderId: '925807401475',
    projectId: 'quickdeliver-d5e46',
    storageBucket: 'quickdeliver-d5e46.firebasestorage.app',
    iosBundleId: 'com.example.quickdeliverFlutterChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuhvRGG0NY56NsSgJVUCGKNNGv_JPdHtE',
    appId: '1:925807401475:web:6e7ae281410ccd954f4c36',
    messagingSenderId: '925807401475',
    projectId: 'quickdeliver-d5e46',
    authDomain: 'quickdeliver-d5e46.firebaseapp.com',
    storageBucket: 'quickdeliver-d5e46.firebasestorage.app',
    measurementId: 'G-4MLEMWLRFK',
  );
}
